### ISSUE TITLE
Shift-Click to flip shortcut not working

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#57] opened 2020-03-26 16:05 UTC
**Describe the bug**
shift-click to flip shortcut not working

**To Reproduce**
1. use selection tool to select the molecule
2. Shift-Click the molecule
4. Nothing happened.

Another thing: The shortcut for both  mirror-vertical and mirror-horizontal is shift-click?

**Comment by MikeWilliams-UK** [comment] 2020-03-26 16:24
@tomyan112 I am not 100% sure without running the application, but I think that you have to Sift-Click on the Flip or Mirror button, so it may be the tool tip which is wrong.

@deadlyvices please confirm.

**Comment by deadlyvices** [comment] 2020-03-26 18:20
Yes, the shortcuts are as you say.  Both are working as expected.  I cannot reproduce this bug.

**Comment by MikeWilliams-UK** [comment] 2020-03-26 18:33
I think that @tomyan112 may be shift clicking on the selected molecule not the button, hence nothing is happening.

**Comment by tomyan112** [comment] 2020-03-26 19:00
> @tomyan112 I am not 100% sure without running the application, but I think that you have to Shift-Click on the **Flip or Mirror buttons**, when a molecule is selected, so it may be the tooltip which is wrong.
> 
> @deadlyvices please confirm.

Then this shortcut is useless, because I can just click the button, not necessary to shift-click

**Comment by MikeWilliams-UK** [comment] 2020-03-26 19:01
@deadlyvices can you please explain to @tomyan112 what the difference is between the two types of clicks on these buttons.

**Comment by deadlyvices** [comment] 2020-03-26 19:11
If you just click the button then you will create a mirror image of the molecule.  All the stereochemistry is inverted.  **Shift**-click on the button, and you will actually rotate it through 180 degrees:  all the stereochemistry is preserved which means that when the molecule inverts the stereobonds invert along with it.

**Comment by MikeWilliams-UK** [comment] 2020-04-02 13:37
Closed as this is by design

**Closed by MikeWilliams-UK** 2020-04-02 13:37 UTC
