### ISSUE TITLE
Incorrect valency

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#46] opened 2020-03-06 18:53 UTC
![image](https://user-images.githubusercontent.com/9064351/76113246-c0506100-601e-11ea-9cae-747f7b95d90c.png)

```xml
<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>cf188ff717bf42788c582874a02c4602</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 10 H 18 Mg 1 Br 1" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="Not requested" concise="C 10 H 18 Mg 1 Br 1" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="Not requested" concise="C 10 H 18 Mg 1 Br 1" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">Unable to calculate</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedAuxInfo">Unable to calculate</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:CalculatedInchikey">Unable to calculate</cml:name>
    <cml:name id="m1.n4" dictRef="chem4word:ResolvedIupacname">Not requested</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="Mg" x2="433.3734" y2="368.75" />
      <cml:atom id="a2" elementType="Br" x2="458.3734" y2="368.75" />
      <cml:atom id="a3" elementType="C" x2="480.024" y2="381.25" />
      <cml:atom id="a4" elementType="C" x2="501.6747" y2="368.75" />
      <cml:atom id="a5" elementType="C" x2="523.3253" y2="381.25" />
      <cml:atom id="a6" elementType="C" x2="544.9759" y2="368.75" />
      <cml:atom id="a7" elementType="Ph" x2="566.6266" y2="381.25" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a2 a3" order="S" />
      <cml:bond id="b2" atomRefs2="a3 a4" order="S" />
      <cml:bond id="b3" atomRefs2="a4 a5" order="S" />
      <cml:bond id="b4" atomRefs2="a5 a6" order="S" />
      <cml:bond id="b5" atomRefs2="a6 a7" order="S" />
      <cml:bond id="b6" atomRefs2="a2 a1" order="S" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>
```

Edit: Added xml markdown to make data clearer

**Comment by MikeWilliams-UK** [comment] 2020-03-06 21:58
@deadlyvices this one's for you to determine what's wrong. You're the chemist.

**Comment by MikeWilliams-UK** [comment] 2020-03-06 21:59
@tomyan112 please confirm which version of Chem4Word.

**Comment by tomyan112** [comment] 2020-03-07 03:24
> @tomyan112 please confirm which version of Chem4Word.

Beta 7

**Comment by tomyan112** [comment] 2020-03-07 18:10
More example
![image](https://user-images.githubusercontent.com/9064351/76150136-facf0200-60e1-11ea-9069-f9d6c79cb1f0.png)

**Comment by deadlyvices** [comment] 2020-03-08 08:31
This is by design.  Nitrogen's valencies were specified as 3 and 5 in the original Chem4Word, and we have carried those definitions through.  Likewise for Br, which has valences 1,3,5 &7, so allowing species like the perbromate ion to be drawn.
If you exceed the first valence on drawing bonds one of these atoms, it assumes the next highest is used and fills unused bonds with hydrogen atoms.

**Comment by MikeWilliams-UK** [comment] 2020-03-10 11:56
Closed as this behaviour is by design.

**Closed by MikeWilliams-UK** 2020-03-10 11:56 UTC
Labels: By Design
