### ISSUE TITLE
Atom selection error

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#49] opened 2020-03-07 10:07 UTC
https://youtu.be/UneB0SY77C8

**Comment by MikeWilliams-UK** [comment] 2020-03-07 11:30
@deadlyvices looking at the video produced by @tomyan112 it may be that ACME is inserting the selected atom instead of the one indicated by the atom dropdown.

**Comment by tomyan112** [comment] 2020-03-10 15:21
I am able to reproduce, a more detailed version is provided for you, https://youtu.be/vw_CSinjnVQ

**Comment by MikeWilliams-UK** [comment] 2020-03-10 15:31
@deadlyvices from @tomyan112 's latest video it looks like the glitch is in the Undo / Redo system.

**Comment by tomyan112** [comment] 2020-04-18 08:45
> @deadlyvices from @tomyan112 's latest video it looks like the glitch is in the Undo / Redo system.

Also happen after using atomic properties
https://www.youtube.com/watch?v=k5AKym1Oy88

**Comment by MikeWilliams-UK** [comment] 2020-04-18 09:01
@tomyan112 this is by design.
After using the property dialogue the atom is selected.
Thus when the atom selection drop down is changed (all) selected atoms are changed to the selected value.

@deadlyvices maybe we should not automatically select the atom or bond after using the dialogues?

**Comment by deadlyvices** [comment] 2020-05-27 11:10
I'm not sure about that.  We select the atom or bond to show the user the object of the last undo operation.  Otherwise it's easy to miss the reversion.

**Comment by MikeWilliams-UK** [comment] 2022-01-28 08:57
Closing as no input from original poster since April 2020

**Closed by MikeWilliams-UK** 2022-01-28 08:57 UTC
Labels: Bug, Can't Reproduce
