### ISSUE TITLE
Variable ring mode does not indicate ring size on first drawing

### ISSUE THREAD

**Issue by deadlyvices** [Chem4Word/Version3-1#23] opened 2020-01-18 14:09 UTC
**Describe the bug**
When drawing a variable ring from a blank structure, the adorner does not tell you how big it is going to be.

**To Reproduce**
Steps to reproduce the behaviour:
1. **Start Word**
2. Click on the Chem4Word  toolbar
2. Click in the document
3. Click the Draw Button
4. Select Variable Ring Mode
5. Click and drag:  the adorner arrow appears, but no ring-size number
1. **Close Word**

**Expected behaviour**
The ring-size should be indicated as a number

**Desktop (please complete the following information):**
Chem4Word 2020 Beta 3 - [3.1.3.7313]

Operating System: Microsoft Windows 10 Enterprise 64bit [10.0.18362.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 32bit [16.0.12325.20288]
Internet Explorer Version: 11.0.18362.592
.Net Framework Runtime: .NET 4.8 (W10 1903) [528040]

Settings Folder: C:\Users\clyde\AppData\Local\Chem4Word.V3
Library Folder: C:\ProgramData\Chem4Word.V3

PlugIns Folder: C:\Program Files (x86)\Chem4Word V3\PlugIns
  Chem4Word.Editor.ACME.dll - [3.1.3.7313]
  Chem4Word.Editor.ChemDoodleWeb702.dll - [3.1.3.7313]
  Chem4Word.Editor.ChemDoodleWeb800.dll - [3.1.3.7313]
  Chem4Word.Renderer.OoXmlV4.dll - [3.1.3.7313]
  Chem4Word.Searcher.ChEBIPlugin.dll - [3.1.3.7313]
  Chem4Word.Searcher.OpsinPlugIn.dll - [3.1.3.7313]
  Chem4Word.Searcher.PubChemPlugIn.dll - [3.1.3.7313]

**Additional context**

**Comment by deadlyvices** [comment] 2020-02-12 21:55
Can't reproduce this easily.  Will keep an eye out for it

**Comment by MikeWilliams-UK** [comment] 2020-05-04 15:51
Closing as unable to reproduce

**Closed** 2020-05-14 12:45 UTC
Labels: Bug, Fixed
