### ISSUE TITLE
Drawing of Markush Bond

### ISSUE THREAD

**Issue by SRHarvey** [Chem4Word/Version3-1#66] opened 2020-05-06 19:28 UTC
*Dear Team,

Thank you for sending me the link to Chem4Word Beta Version 3.1.

I have drawn the following structure:
![image](https://user-images.githubusercontent.com/64924747/81218152-9a99f680-8f92-11ea-987a-0992eb46fbad.png)

 
I would like to draw a bond from the R4 “atom” to the center of the six-membered ring, to indicate that the R4 group could be placed in any position on the ring (Markush bond?).    When I try to do this, Chem4Word places a methyl group at the end of the bond in the center of the six-membered ring.  Can Chem4Word draw a bond without placing an atom at the end of the bond?    Alternatively, can Chem4Word remove the display of terminal carbon atoms?
I would appreciate any information you could give me.  Thank you.
Suzanne R. Harvey

*Is your feature request related to a problem? Please describe.**

A clear and concise description [in English] of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**I would like to be able to draw a bond from an atom with no atom at the other end of the bond.

A clear and concise description [in English] of what you want to happen.

**Describe alternatives you've considered**I have drawn most of the structure in Chem4Word, used the Snipping Tool to move it into another Word document and then draw the one line (bond) I need between the R group and the center of the ring.

A clear and concise description [in English] of any alternative solutions or features you've considered. If Chem4Word could turn off the display of terminal carbons, that would solve my problem.

**Additional context**

Edited to remove user's email address.

**Comment by MikeWilliams-UK** [comment] 2020-05-06 19:31
Duplicate of https://github.com/Chem4Word/Version3-1/issues/26

**Comment by MikeWilliams-UK** [comment] 2020-05-06 19:44
>  Alternatively, can Chem4Word remove the display of terminal carbon atoms?

Yes; In the editor right-click on the atom to bring up the properties dialogue.
Then make sure the Explicit checkbox is empty.
![image](https://user-images.githubusercontent.com/13162784/81221157-5c282a00-8fda-11ea-8fd9-adb1cc88451d.png)

**Comment by deadlyvices** [comment] 2020-05-07 07:24
Thanks for your comment @SRHarvey.    We are aware that other tools allow Variable Points of Attachment.  This is something we should provide in Chem4Word.  
We are planning a feature roadmap for Chem4Word and will look at whether we can also provide VPAs, but we are a very small team and so we need to prioritise.  
Regards
Clyde Davies

**Comment by SRHarvey** [comment] 2020-05-07 17:00
Thank you very much!

**Comment by MikeWilliams-UK** [comment] 2020-05-11 09:16
I am closing this issue as it is a duplicate of one we have on our roadmap.

**Closed by MikeWilliams-UK** 2020-05-11 09:16 UTC
Labels: Duplicate
