### ISSUE TITLE
Unable to add bond to R Atom

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#20] opened 2020-01-18 07:10 UTC
**Describe the bug**
A clear and concise description [in English] of what the bug is.

**To Reproduce**
First draw a R, then add carbon chain
![image](https://user-images.githubusercontent.com/9064351/72660160-8e4e5580-3a04-11ea-9e71-b44210c6d4bc.png)

This results in molecule like R-X can't be drawn

**Expected behavior**
A clear and concise description [in English] of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7/8.1/10 Home/Professional]
 - Word Version [e.g. 2016/O365/2019 Home/Business/Professional]
 - Please also gather system information from "Help" --> "System Info" in Chem4Word Ribbon

**Additional context**

**Comment by deadlyvices** [comment] 2020-01-18 14:00
I've just reproduced this.  Only happens if you select R as an **atom ** from the periodic table.  I think it's because its valence is set to 0.

**Comment by MikeWilliams-UK** [comment] 2020-02-01 00:13
Fixed in Beta 5

**Closed by MikeWilliams-UK** 2020-02-01 00:13 UTC
Labels: Bug, Fixed
