### ISSUE TITLE
Double bond placement error

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#33] opened 2020-02-09 17:16 UTC
After I specifically set the placement as clockwise and anticlockwise, it still display as none.
![image](https://user-images.githubusercontent.com/9064351/74106525-b57ee980-4ba2-11ea-9091-6aa21f9c24c7.png)
![image](https://user-images.githubusercontent.com/9064351/74106545-d6473f00-4ba2-11ea-954e-88a632dcd0c2.png)

Another example
![image](https://user-images.githubusercontent.com/9064351/74106601-49e94c00-4ba3-11ea-9059-a1ee21c9373a.png)

**Comment by tomyan112** [comment] 2020-02-09 18:24
I was trying to draw norbornene and the double bond turned in to a little dot.
![2020-02-10_02-22-24](https://user-images.githubusercontent.com/9064351/74107558-63db5c80-4bac-11ea-939e-13480ebdff31.png)

**Comment by MikeWilliams-UK** [comment] 2020-02-09 18:28
Can you please post the CML for this structure to allow us to investigate?

**Comment by tomyan112** [comment] 2020-02-10 01:16
> Can you please post the CML for this structure to allow us to investigate?

<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>c174876665c64c25ae3b85669c20c9e8</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 7 H 10" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="C7H10" concise="C 7 H 10" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="C1CC2CC1C=C2" concise="C 7 H 10" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">1S/C7H10/c1-2-7-4-3-6(1)5-7/h1-2,6-7H,3-5H2</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedAuxInfo">1/0/N:2,4,3,5,7,1,6/E:(1,2)(3,4)(6,7)/rA:7nCCCCCCC/rB:s1;s1;d2;s3;s4s5;s1s6;/rC:34.463,-27.2036,0;33.118,-27.564,0;35.808,-27.564,0;33.8142,-26.3581,0;36.5042,-26.3581,0;35.1592,-25.9977,0;34.7988,-24.6527,0;</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:CalculatedInchikey">JFNLZVQOOSMTJK-UHFFFAOYSA-N</cml:name>
    <cml:name id="m1.n4" dictRef="chem4word:ResolvedIupacname">bicyclo[2.2.1]hept-2-ene</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="C" x2="495" y2="390.7313" />
      <cml:atom id="a2" elementType="C" x2="475.6815" y2="395.9077" />
      <cml:atom id="a3" elementType="C" x2="514.3185" y2="395.9077" />
      <cml:atom id="a4" elementType="C" x2="485.6815" y2="378.5872" />
      <cml:atom id="a5" elementType="C" x2="524.3185" y2="378.5872" />
      <cml:atom id="a6" elementType="C" x2="505" y2="373.4108" />
      <cml:atom id="a7" elementType="C" x2="499.8236" y2="354.0923" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a2 a1" order="S" />
      <cml:bond id="b2" atomRefs2="a1 a3" order="S" />
      <cml:bond id="b3" atomRefs2="a2 a4" order="D" c4w:placement="Anticlockwise" />
      <cml:bond id="b4" atomRefs2="a3 a5" order="S" />
      <cml:bond id="b5" atomRefs2="a4 a6" order="S" />
      <cml:bond id="b6" atomRefs2="a6 a5" order="S" />
      <cml:bond id="b7" atomRefs2="a6 a7" order="S" />
      <cml:bond id="b8" atomRefs2="a7 a1" order="S" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>

**Comment by MikeWilliams-UK** [comment] 2020-02-10 08:26
Possible duplicate of #25

**Comment by MikeWilliams-UK** [comment] 2020-02-10 14:24
In the attached image I have turned on a couple of diagnostic features which allow us to diagnose issues.
Green spots show the detected centre of rings.
The dotted lines show how the extra bond line which is initially parallel to and the same size as main bond line is clipped.

**In the case of this structure, it is the calculation of the ring centre which is at fault.**

![image](https://user-images.githubusercontent.com/13162784/74157576-6bcce800-4c10-11ea-9826-7c380708f626.png)

**Comment by tomyan112** [comment] 2020-02-11 10:00
> In the attached image I have turned on a couple of diagnostic features which allow us to diagnose issues.
> 
> Green spots show the detected centre of rings.

> The dotted lines show how the extra bond line which is initially parallel to and the same size as the main bond line is clipped.
> 
> **In the case of this structure, it is the calculation of the ring centre which is at fault.**
> 
> ![image](https://user-images.githubusercontent.com/13162784/74157576-6bcce800-4c10-11ea-9826-7c380708f626.png)
I tried to draw this
![image](https://user-images.githubusercontent.com/9064351/74226866-4915fe80-4cf8-11ea-8fc8-4713acf91fb0.png)
But I get this
![image](https://user-images.githubusercontent.com/9064351/74226895-50d5a300-4cf8-11ea-8d3f-b5e611d0c853.png)
A video has been made for your reference. https://youtu.be/jNpb6hgyZFI

<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>0d341c44b49e438fa27d479c90e69fcd</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 10 H 17 O 3" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="Not requested" concise="C 10 H 17 O 3" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="Not requested" concise="C 10 H 17 O 3" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">Unable to calculate</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedAuxInfo">Unable to calculate</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:CalculatedInchikey">Unable to calculate</cml:name>
    <cml:name id="m1.n4" dictRef="chem4word:ResolvedIupacname">Not requested</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="C" x2="482.6795" y2="395" />
      <cml:atom id="a2" elementType="C" x2="482.6795" y2="375" />
      <cml:atom id="a3" elementType="C" x2="500" y2="365" />
      <cml:atom id="a4" elementType="C" x2="517.3205" y2="375" />
      <cml:atom id="a5" elementType="C" x2="517.3205" y2="395" />
      <cml:atom id="a6" elementType="C" x2="500" y2="405" />
      <cml:atom id="a7" elementType="O" x2="500" y2="345" />
      <cml:atom id="a8" elementType="C" x2="527.3205" y2="357.6795" />
      <cml:atom id="a9" elementType="CO2H" x2="537.3205" y2="375" />
      <cml:atom id="a10" elementType="C" x2="577.3205" y2="375" />
      <cml:atom id="a11" elementType="C" x2="617.3205" y2="375" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a1 a2" order="S" />
      <cml:bond id="b2" atomRefs2="a2 a3" order="S" />
      <cml:bond id="b3" atomRefs2="a3 a4" order="S" />
      <cml:bond id="b4" atomRefs2="a4 a5" order="S" />
      <cml:bond id="b5" atomRefs2="a5 a6" order="S" />
      <cml:bond id="b6" atomRefs2="a6 a1" order="S" />
      <cml:bond id="b7" atomRefs2="a3 a7" order="D" />
      <cml:bond id="b8" atomRefs2="a4 a8" order="S" />
      <cml:bond id="b9" atomRefs2="a9 a4" order="S" />
      <cml:bond id="b10" atomRefs2="a9 a10" order="S" />
      <cml:bond id="b11" atomRefs2="a10 a11" order="S" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>

**Comment by MikeWilliams-UK** [comment] 2020-02-11 10:22
@tomyan112 this has been closed because it is a duplicate, non related issues have been created for off-topic posts

**Closed by MikeWilliams-UK** 2020-02-11 10:22 UTC
Labels: Bug, Duplicate

**Comment by MikeWilliams-UK** [comment] 2020-02-11 10:25
@tomyan112 I have created two new issues for unrelated problems
#34, #35

**Comment by MikeWilliams-UK** [comment] 2020-02-12 19:54
Closed as duplicate of https://github.com/Chem4Word/Version3-1/issues/25
